//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> id_project { get; set; }
        public Nullable<int> id_owner { get; set; }
        public Nullable<int> id_creator { get; set; }
        public Nullable<int> id_state { get; set; }
        public string Title { get; set; }
        public string Descritpion { get; set; }
        public byte[] Date { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual State State { get; set; }
        public virtual User Creator { get; set; }
        public virtual User Owner { get; set; }
    }
}
